[package]
name = "abc222"
version = "0.1.0"
authors = ["shimo <shimo.8810@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "0.4.3"

[profile.release]
lto = true
panic = 'abort'
