[package]
name = "abc229"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.10.1"
itertools-num = "0.1.3"
num = "0.4.0"
proconio = { version = "0.4.3", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
