[package]
name = "tessoku-book"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.10.5"
num = "0.4.0"
petgraph = "0.6.2"
proconio = { version = "0.4.3", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
