[package]
name = "abs"
version = "0.1.0"
authors = ["shimo8810 <shimo.8810@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = {version = "0.4.1", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
