[package]
name = "abc231"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
petgraph = "0.6.0"
proconio = { version = "0.4.3", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
