[package]
name = "abc234"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.10.3"
maplit = "1.0.2"
num = "0.4.0"
petgraph = "0.6.0"
proconio = { version = "0.4.3", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
